version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./code:/usr/src/server
    depends_on:
      - mysql_server

  mysql_server:
    image: mysql

    environment:
      MYSQL_DATABASE: newdb
      MYSQL_USER: root
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password


